#!/bin/bash
echo "### Run advanced ###"

function qemu(){
  echo "=> enable quemu"
  docker run --rm --privileged multiarch/qemu-user-static:register --reset
}

function manifest(){
  echo "=> install manifest-tool"
  local URL=https://github.com/estesp/manifest-tool/releases/download/v0.6.0/manifest-tool-linux-amd64
  curl -sLo ./manifest-tool ${URL}
  chmod +x ./manifest-tool
}

function multiarch(){
echo "=> push multiarch"
echo "${DOCKER_REPO}:${VERSION}"

ARCH="linux/arm,linux/amd64"
./manifest-tool push from-args \
--platforms ${ARCH} \
--template ${DOCKER_REPO}:${VERSION}-ARCH \
--target ${DOCKER_REPO}:${VERSION}
}

function info(){
local folder="${1}"
ARCH=$(basename "${folder}")
VERSION=$(basename $(dirname "${folder}"))

#echo arch=${ARCH}
#echo version=${VERSION}
}

qemu
manifest

for df in $(find . -type f -name 'Dockerfile*');
do
  df_path=$(dirname ${df})
  info "${df_path}"
#  echo "Building ${df_path}"
  
  URL=https://github.com/containous/traefik/releases/download/v${VERSION}/traefik_linux-${ARCH}
  curl -sLo ${df_path}/traefik ${URL}
  chmod +x ${df_path}/traefik
  
  echo "Building ${DOCKER_REPO}:${VERSION}-${ARCH}"
  docker image build -t ${DOCKER_REPO}:${VERSION}-${ARCH} -f "${df}" "${df_path}"
done

for versions in $(ls -1d */ |sort -d -r); do
  if [[ "${versions}" != "hooks" ]]; then
    if [[ $(ls -1 ${versions} | wc -l) -gt 1 ]]; then
      multiarch  
    fi 
  fi
done


latest="$(ls -1d */ |sort -d -r | grep -v hooks|  head -n 1 | cut -f1 -d'/')"
docker tag  ${DOCKER_REPO}:${latest} ${DOCKER_REPO}:latest
